-- COMLAB Supabase / PostgreSQL schema
-- Run this file in the Supabase SQL editor.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Core tables used by the PHP app

create table if not exists public.users (
  user_id         bigint generated by default as identity primary key,
  username        text not null unique,
  email           text not null unique,
  password_hash   text not null,
  first_name      text not null,
  last_name       text not null,
  role            text not null check (role in ('Administrator', 'Faculty')),
  hr_employee_id  text unique,
  synced_from_hr  smallint not null default 0 check (synced_from_hr in (0, 1)),
  department      text,
  contact_number  text,
  is_active       smallint not null default 1 check (is_active in (0, 1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  last_login      timestamptz
);

drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create index if not exists idx_users_role on public.users(role);
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_users_hr_employee_id on public.users(hr_employee_id);
create index if not exists idx_users_active_role on public.users(role, is_active);

create table if not exists public.user_sessions (
  session_id   bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(user_id) on delete cascade,
  auth_token   text not null unique,
  ip_address   text,
  user_agent   text,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  is_active    smallint not null default 1 check (is_active in (0, 1))
);

create index if not exists idx_user_sessions_token on public.user_sessions(auth_token);
create index if not exists idx_user_sessions_user on public.user_sessions(user_id);

create table if not exists public.locations (
  location_id            bigint generated by default as identity primary key,
  lab_name               text not null,
  lab_code               text not null unique,
  building               text,
  floor                  text,
  room_number            text,
  capacity               integer not null default 0,
  operating_hours_start  time not null default time '08:00',
  operating_hours_end    time not null default time '18:00',
  operating_days         text default 'Monday-Friday',
  description            text,
  is_active              smallint not null default 1 check (is_active in (0, 1)),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_locations_updated_at on public.locations;
create trigger trg_locations_updated_at
before update on public.locations
for each row execute function public.set_updated_at();

create index if not exists idx_locations_lab_code on public.locations(lab_code);
create index if not exists idx_locations_active on public.locations(is_active);

create table if not exists public.devices (
  device_id              bigint generated by default as identity primary key,
  device_code            text not null unique,
  device_type            text not null check (device_type in ('Desktop', 'Laptop', 'Monitor', 'Keyboard', 'Mouse', 'Printer', 'Other')),
  brand                  text,
  model                  text,
  serial_number          text,
  specifications         text,
  purchase_date          date,
  warranty_expiry        date,
  status                 text not null default 'Available' check (status in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  location_id            bigint references public.locations(location_id) on delete set null,
  assigned_to            bigint references public.users(user_id) on delete set null,
  last_maintenance_date  date,
  next_maintenance_date  date,
  notes                  text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_devices_updated_at on public.devices;
create trigger trg_devices_updated_at
before update on public.devices
for each row execute function public.set_updated_at();

create index if not exists idx_devices_code on public.devices(device_code);
create index if not exists idx_devices_status on public.devices(status);
create index if not exists idx_devices_location on public.devices(location_id);

create table if not exists public.device_maintenance_logs (
  maintenance_id     bigint generated by default as identity primary key,
  device_id          bigint not null references public.devices(device_id) on delete cascade,
  performed_by       bigint not null references public.users(user_id) on delete cascade,
  maintenance_type   text not null check (maintenance_type in ('Repair', 'Preventive Maintenance', 'Inspection', 'Upgrade')),
  issue_description  text,
  action_taken       text,
  parts_replaced     text,
  status_before      text not null check (status_before in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  status_after       text not null check (status_after in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  cost               numeric(10,2) not null default 0.00,
  start_datetime     timestamptz not null default now(),
  end_datetime       timestamptz,
  created_at         timestamptz not null default now()
);

create index if not exists idx_device_maintenance_device on public.device_maintenance_logs(device_id);
create index if not exists idx_device_maintenance_performed_by on public.device_maintenance_logs(performed_by);

create table if not exists public.faculty_schedules (
  schedule_id     bigint generated by default as identity primary key,
  faculty_id      bigint not null references public.users(user_id) on delete cascade,
  assigned_by     bigint not null references public.users(user_id) on delete cascade,
  location_id     bigint not null references public.locations(location_id) on delete cascade,
  class_name      text not null,
  day_of_week     text not null,
  start_time      time not null,
  end_time        time not null,
  duration_hours  numeric(4,2) not null,
  semester_start  date not null,
  semester_end    date not null,
  department      text not null,
  notes           text,
  is_active       smallint not null default 1 check (is_active in (0, 1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists trg_faculty_schedules_updated_at on public.faculty_schedules;
create trigger trg_faculty_schedules_updated_at
before update on public.faculty_schedules
for each row execute function public.set_updated_at();

create index if not exists idx_faculty_schedules_faculty on public.faculty_schedules(faculty_id);
create index if not exists idx_faculty_schedules_location on public.faculty_schedules(location_id);
create index if not exists idx_faculty_schedules_active on public.faculty_schedules(is_active);
create index if not exists idx_faculty_schedules_semester on public.faculty_schedules(semester_start, semester_end);
create unique index if not exists uq_faculty_schedules_seed_key
  on public.faculty_schedules(faculty_id, class_name, semester_start);
alter table public.faculty_schedules
  add column if not exists source_system text;
alter table public.faculty_schedules
  add column if not exists source_reference text;
alter table public.faculty_schedules
  add column if not exists synced_from_hr smallint not null default 0 check (synced_from_hr in (0, 1));
create index if not exists idx_faculty_schedules_source_reference on public.faculty_schedules(source_reference);

create table if not exists public.schedule_attendance (
  attendance_id    bigint generated by default as identity primary key,
  schedule_id      bigint not null references public.faculty_schedules(schedule_id) on delete cascade,
  faculty_id       bigint not null references public.users(user_id) on delete cascade,
  attendance_date  date not null,
  status           text not null default 'Absent' check (status in ('Present', 'Absent', 'Excused')),
  checked_in_at    timestamptz,
  marked_by_system smallint not null default 0 check (marked_by_system in (0, 1)),
  notes            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (schedule_id, attendance_date)
);

drop trigger if exists trg_schedule_attendance_updated_at on public.schedule_attendance;
create trigger trg_schedule_attendance_updated_at
before update on public.schedule_attendance
for each row execute function public.set_updated_at();

create index if not exists idx_schedule_attendance_faculty_date on public.schedule_attendance(faculty_id, attendance_date);
create index if not exists idx_schedule_attendance_schedule on public.schedule_attendance(schedule_id);
create index if not exists idx_schedule_attendance_date on public.schedule_attendance(attendance_date);

create table if not exists public.lab_usage_logs (
  usage_log_id        bigint generated by default as identity primary key,
  location_id         bigint not null references public.locations(location_id) on delete cascade,
  faculty_id          bigint references public.users(user_id) on delete set null,
  schedule_id         bigint references public.faculty_schedules(schedule_id) on delete set null,
  recorded_by         bigint references public.users(user_id) on delete set null,
  usage_date          date not null default current_date,
  session_start       timestamptz not null,
  session_end         timestamptz,
  participant_count   integer not null default 0,
  subject_code        text,
  source_system       text,
  source_reference    text,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (session_end is null or session_end >= session_start)
);

drop trigger if exists trg_lab_usage_logs_updated_at on public.lab_usage_logs;
create trigger trg_lab_usage_logs_updated_at
before update on public.lab_usage_logs
for each row execute function public.set_updated_at();

create index if not exists idx_lab_usage_logs_usage_date on public.lab_usage_logs(usage_date);
create index if not exists idx_lab_usage_logs_location on public.lab_usage_logs(location_id);
create index if not exists idx_lab_usage_logs_faculty on public.lab_usage_logs(faculty_id);
create index if not exists idx_lab_usage_logs_schedule on public.lab_usage_logs(schedule_id);
create unique index if not exists uq_lab_usage_logs_source_reference
  on public.lab_usage_logs(source_reference)
  where source_reference is not null;

create table if not exists public.requests (
  request_id             bigint generated by default as identity primary key,
  request_type           text not null check (request_type in ('Maintenance', 'Unit')),
  submitted_by           bigint not null references public.users(user_id) on delete cascade,
  reviewed_by            bigint references public.users(user_id) on delete set null,
  department             text not null,
  location_id            bigint references public.locations(location_id) on delete set null,
  location_text          text,
  device_id              bigint references public.devices(device_id) on delete set null,
  issue_description      text,
  date_needed            date,
  device_type_needed     text,
  specifications_needed  text,
  quantity               integer,
  justification          text,
  status                 text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected', 'Completed')),
  rejection_reason       text,
  reviewed_at            timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_requests_updated_at on public.requests;
create trigger trg_requests_updated_at
before update on public.requests
for each row execute function public.set_updated_at();

create index if not exists idx_requests_submitted_by on public.requests(submitted_by);
create index if not exists idx_requests_status on public.requests(status);
create index if not exists idx_requests_created_at on public.requests(created_at);

create table if not exists public.audit_logs (
  log_id       bigint generated by default as identity primary key,
  user_id      bigint references public.users(user_id) on delete set null,
  action_type  text not null,
  target_type  text check (target_type in ('User', 'Device', 'Location', 'Assignment', 'Request', 'Maintenance', 'System')),
  target_id    bigint,
  description  text not null,
  old_value    text,
  new_value    text,
  ip_address   text,
  user_agent   text,
  created_at   timestamptz not null default now()
);

create index if not exists idx_audit_logs_user on public.audit_logs(user_id);
create index if not exists idx_audit_logs_action on public.audit_logs(action_type);
create index if not exists idx_audit_logs_target on public.audit_logs(target_type, target_id);

create table if not exists public.login_attempts (
  ip_address     text primary key,
  attempt_count   integer not null default 0,
  last_attempt    timestamptz not null default now(),
  locked_until    timestamptz
);

create index if not exists idx_login_attempts_locked on public.login_attempts(locked_until);

-- Department integration tables

create table if not exists public.departments (
  department_id    bigint generated by default as identity primary key,
  department_code  text not null unique,
  department_name  text not null unique,
  description      text,
  is_active        smallint not null default 1 check (is_active in (0, 1)),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

drop trigger if exists trg_departments_updated_at on public.departments;
create trigger trg_departments_updated_at
before update on public.departments
for each row execute function public.set_updated_at();

create table if not exists public.integration_record_types (
  record_type_id    bigint generated by default as identity primary key,
  record_type_code  text not null unique,
  record_type_name  text not null,
  data_domain       text not null,
  description       text,
  is_active         smallint not null default 1 check (is_active in (0, 1)),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

drop trigger if exists trg_integration_record_types_updated_at on public.integration_record_types;
create trigger trg_integration_record_types_updated_at
before update on public.integration_record_types
for each row execute function public.set_updated_at();

create table if not exists public.integration_routes (
  route_id               bigint generated by default as identity primary key,
  flow_order             smallint not null default 1,
  sender_department_id   bigint not null references public.departments(department_id) on delete cascade,
  receiver_department_id  bigint not null references public.departments(department_id) on delete cascade,
  record_type_id         bigint not null references public.integration_record_types(record_type_id) on delete cascade,
  notes                  text,
  is_active              smallint not null default 1 check (is_active in (0, 1)),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (sender_department_id, receiver_department_id, record_type_id)
);

drop trigger if exists trg_integration_routes_updated_at on public.integration_routes;
create trigger trg_integration_routes_updated_at
before update on public.integration_routes
for each row execute function public.set_updated_at();

create index if not exists idx_integration_routes_sender on public.integration_routes(sender_department_id);
create index if not exists idx_integration_routes_receiver on public.integration_routes(receiver_department_id);
create index if not exists idx_integration_routes_record_type on public.integration_routes(record_type_id);

create table if not exists public.integration_documents (
  document_id            uuid primary key default gen_random_uuid(),
  route_id               bigint references public.integration_routes(route_id) on delete set null,
  record_type_id         bigint not null references public.integration_record_types(record_type_id) on delete restrict,
  sender_department_id   bigint not null references public.departments(department_id) on delete restrict,
  receiver_department_id bigint not null references public.departments(department_id) on delete restrict,
  subject_type           text not null check (subject_type in ('student', 'staff', 'faculty', 'general', 'system')),
  subject_ref            text,
  title                  text not null,
  source_system          text,
  source_reference       text,
  status                 text not null default 'draft' check (status in ('draft', 'sent', 'received', 'acknowledged', 'archived')),
  payload                jsonb not null default '{}'::jsonb,
  sent_at                timestamptz,
  received_at            timestamptz,
  acknowledged_at        timestamptz,
  created_by_user_id     bigint references public.users(user_id) on delete set null,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_integration_documents_updated_at on public.integration_documents;
create trigger trg_integration_documents_updated_at
before update on public.integration_documents
for each row execute function public.set_updated_at();

create index if not exists idx_integration_documents_status on public.integration_documents(status);
create index if not exists idx_integration_documents_sender on public.integration_documents(sender_department_id);
create index if not exists idx_integration_documents_receiver on public.integration_documents(receiver_department_id);
create index if not exists idx_integration_documents_record_type on public.integration_documents(record_type_id);
create index if not exists idx_integration_documents_subject_ref on public.integration_documents(subject_ref);
create index if not exists idx_integration_documents_source_reference on public.integration_documents(source_reference);

-- Views used by the current COMLAB UI

create or replace view public.dashboard_summary as
select
  (select count(*) from public.users where is_active = 1) as total_active_users,
  (select count(*) from public.users where role = 'Administrator' and is_active = 1) as total_admins,
  (select count(*) from public.users where role = 'Faculty' and is_active = 1) as total_faculty,
  (select count(*) from public.devices) as total_devices,
  (select count(*) from public.devices where status = 'Available') as devices_available,
  (select count(*) from public.devices where status = 'Under Repair') as devices_under_repair,
  (select count(*) from public.devices where status = 'Damaged') as devices_damaged,
  (select count(*) from public.locations where is_active = 1) as total_labs,
  (select count(*) from public.faculty_schedules where is_active = 1) as active_schedules,
  (select count(*) from public.requests where status = 'Pending') as pending_requests;

create or replace view public.faculty_presence_summary as
select
  u.user_id,
  concat(u.first_name, ' ', u.last_name) as faculty_name,
  u.department,
  count(distinct fs.schedule_id) as active_schedules,
  count(sa.attendance_id) as total_sessions,
  sum(case when sa.status = 'Present' then 1 else 0 end) as present_count,
  sum(case when sa.status = 'Absent' then 1 else 0 end) as absent_count,
  sum(case when sa.status = 'Excused' then 1 else 0 end) as excused_count,
  round(100.0 * sum(case when sa.status = 'Present' then 1 else 0 end) / nullif(count(sa.attendance_id), 0), 1) as attendance_rate_pct
from public.users u
left join public.faculty_schedules fs on fs.faculty_id = u.user_id and fs.is_active = 1
left join public.schedule_attendance sa on sa.faculty_id = u.user_id
where u.role = 'Faculty' and u.is_active = 1
group by u.user_id;

create or replace view public.integration_message_feed as
select
  d.document_id,
  rt.record_type_code,
  rt.record_type_name,
  sd.department_name as sender_department,
  rd.department_name as receiver_department,
  d.title,
  d.subject_type,
  d.status,
  d.sent_at,
  d.received_at,
  d.created_at
from public.integration_documents d
join public.integration_record_types rt on rt.record_type_id = d.record_type_id
left join public.departments sd on sd.department_id = d.sender_department_id
left join public.departments rd on rd.department_id = d.receiver_department_id;

-- Seed department directory

insert into public.departments (department_code, department_name, description)
values
  ('REGISTRAR', 'Registrar', 'Student enrollment and academic records hub.'),
  ('CASHIER', 'Cashier', 'Payments and financial clearing.'),
  ('CLINIC', 'Clinic', 'Medical and health services office.'),
  ('GUIDANCE', 'Guidance Office', 'Counseling and student support.'),
  ('PREFECT', 'Prefect Office', 'Discipline and student conduct.'),
  ('COMLAB', 'Computer Laboratory', 'Computer laboratory operations.'),
  ('CRAD', 'CRAD Department', 'Student activities and programs.'),
  ('HR', 'HR Department', 'Human resources and staffing.'),
  ('PMED', 'PMED Department', 'Monitoring, evaluation, and development.'),
  ('ADMIN', 'School Administration', 'School-wide administration and approvals.')
on conflict (department_code) do nothing;

insert into public.integration_record_types (record_type_code, record_type_name, data_domain, description)
values
  ('student_enrollment_data', 'Student Enrollment Data', 'student', 'Enrollment details sent from Registrar to Cashier.'),
  ('payment_confirmation', 'Payment Confirmation', 'finance', 'Cashier confirmation sent to Registrar.'),
  ('medical_clearance', 'Medical Clearance', 'health', 'Clinic clearance sent to Registrar.'),
  ('counseling_reports', 'Counseling Reports', 'health', 'Counseling reports received by Registrar.'),
  ('discipline_records', 'Discipline Records', 'discipline', 'Discipline information received by Registrar.'),
  ('activity_participation_records', 'Activity Participation Records', 'student', 'Activity participation records from CRAD.'),
  ('student_personal_information', 'Student Personal Information', 'student', 'Shared student profile information.'),
  ('student_list', 'Student List', 'student', 'Student listing shared with recipient offices.'),
  ('enrollment_statistics', 'Enrollment Statistics', 'student', 'Enrollment counts and trends.'),
  ('payroll_data', 'Payroll Data', 'staff', 'Payroll-related data for Cashier.'),
  ('financial_reports', 'Financial Reports', 'finance', 'Financial reports sent to PMED.'),
  ('health_incident_reports', 'Health Incident Reports', 'health', 'Incident reports from Prefect to Clinic.'),
  ('health_reports', 'Health Reports', 'health', 'Health reports from Clinic to Guidance.'),
  ('medical_service_reports', 'Medical Service Reports', 'health', 'Clinic reporting to PMED.'),
  ('student_academic_records', 'Student Academic Records', 'student', 'Academic records used by Guidance.'),
  ('health_concerns', 'Health Concerns', 'health', 'Concerns forwarded from Guidance to Clinic.'),
  ('discipline_reports', 'Discipline Reports', 'discipline', 'Reports shared between Guidance and Prefect.'),
  ('incident_reports', 'Incident Reports', 'discipline', 'Incident reports shared by Prefect.'),
  ('discipline_statistics', 'Discipline Statistics', 'discipline', 'Discipline statistics sent to PMED.'),
  ('staff_list', 'Staff List', 'staff', 'Staff list received by the Computer Laboratory.'),
  ('user_accounts', 'User Accounts', 'staff', 'User account data for laboratory access.'),
  ('pmed_faculty_attendance', 'PMED Faculty Attendance', 'staff', 'Faculty attendance information from PMED.'),
  ('laboratory_usage_reports', 'Laboratory Usage Reports', 'lab', 'Usage reports sent to PMED.'),
  ('student_recommendations', 'Student Recommendations', 'student', 'Recommendations coming from Guidance.'),
  ('student_activity_records', 'Student Activity Records', 'student', 'Activity records sent back to Registrar.'),
  ('program_reports', 'Program Reports', 'program', 'Program-level reports from CRAD.'),
  ('program_activity_reports', 'Program Activity Reports', 'program', 'Program activity reports sent to PMED.'),
  ('staff_evaluation_feedback', 'Staff Evaluation Feedback', 'staff', 'Feedback received by HR from PMED.'),
  ('faculty_list', 'Faculty List', 'staff', 'Faculty list shared with Registrar.'),
  ('employee_performance_records', 'Employee Performance Records', 'staff', 'Performance records reported by HR.'),
  ('evaluation_reports', 'Evaluation Reports', 'program', 'School administration evaluation reports from PMED.')
on conflict (record_type_code) do nothing;

insert into public.integration_routes (flow_order, sender_department_id, receiver_department_id, record_type_id, notes)
select v.flow_order, s.department_id, r.department_id, t.record_type_id, v.notes
from (
  values
    (1,  'REGISTRAR', 'CASHIER', 'student_enrollment_data',      'Registrar sends enrollment data to Cashier.'),
    (2,  'CASHIER',   'REGISTRAR', 'payment_confirmation',        'Cashier sends payment confirmation to Registrar.'),
    (3,  'REGISTRAR', 'CLINIC',    'student_personal_information','Registrar shares student personal information with Clinic.'),
    (4,  'REGISTRAR', 'GUIDANCE',  'student_personal_information','Registrar shares student personal information with Guidance.'),
    (5,  'REGISTRAR', 'PREFECT',   'student_personal_information','Registrar shares student personal information with Prefect.'),
    (6,  'REGISTRAR', 'COMLAB',    'student_list',                'Registrar shares the student list with the Computer Laboratory.'),
    (7,  'REGISTRAR', 'CRAD',      'student_list',                'Registrar shares the student list with CRAD.'),
    (8,  'REGISTRAR', 'PMED',      'enrollment_statistics',       'Registrar sends enrollment statistics to PMED.'),
    (9,  'CLINIC',    'REGISTRAR', 'medical_clearance',           'Clinic sends medical clearance to Registrar.'),
    (10, 'GUIDANCE',  'REGISTRAR', 'counseling_reports',         'Guidance sends counseling reports to Registrar.'),
    (11, 'PREFECT',   'REGISTRAR', 'discipline_records',         'Prefect sends discipline records to Registrar.'),
    (12, 'PREFECT',   'CLINIC',    'health_incident_reports',    'Prefect sends health incident reports to Clinic.'),
    (13, 'CLINIC',    'GUIDANCE',  'health_reports',             'Clinic sends health reports to Guidance.'),
    (14, 'CLINIC',    'PMED',      'medical_service_reports',    'Clinic sends medical service reports to PMED.'),
    (15, 'GUIDANCE',  'CLINIC',    'health_concerns',            'Guidance sends health concerns to Clinic.'),
    (16, 'GUIDANCE',  'PREFECT',   'discipline_reports',         'Guidance sends discipline reports to Prefect.'),
    (17, 'PREFECT',   'GUIDANCE',  'discipline_reports',         'Prefect sends discipline reports to Guidance.'),
    (18, 'PREFECT',   'CLINIC',    'incident_reports',           'Prefect sends incident reports to Clinic.'),
    (19, 'PREFECT',   'PMED',      'discipline_statistics',      'Prefect sends discipline statistics to PMED.'),
    (20, 'HR',        'CASHIER',   'payroll_data',               'HR sends payroll data to Cashier.'),
    (21, 'HR',        'REGISTRAR', 'faculty_list',               'HR sends the faculty list to Registrar.'),
    (22, 'HR',        'PMED',      'employee_performance_records','HR sends employee performance records to PMED.'),
    (23, 'PMED',      'COMLAB',    'pmed_faculty_attendance',    'PMED sends faculty attendance data to the Computer Laboratory.'),
    (24, 'COMLAB',    'PMED',      'laboratory_usage_reports',   'Computer Laboratory sends laboratory usage reports to PMED.'),
    (25, 'CRAD',      'REGISTRAR', 'activity_participation_records','CRAD sends activity participation records to Registrar.'),
    (26, 'CRAD',      'REGISTRAR', 'student_activity_records',   'CRAD sends student activity records to Registrar.'),
    (27, 'CRAD',      'PMED',      'program_reports',            'CRAD sends program reports to PMED.'),
    (28, 'CRAD',      'PMED',      'program_activity_reports',   'CRAD sends program activity reports to PMED.'),
    (29, 'GUIDANCE',  'CRAD',      'student_recommendations',    'Guidance sends student recommendations to CRAD.'),
    (30, 'CASHIER',   'PMED',      'financial_reports',          'Cashier sends financial reports to PMED.'),
    (31, 'PMED',      'ADMIN',     'evaluation_reports',         'PMED sends evaluation reports to School Administration.'),
    (32, 'PMED',      'HR',        'staff_evaluation_feedback',  'PMED sends staff evaluation feedback to HR.'),
    (33, 'HR',        'COMLAB',    'staff_list',                 'HR sends the staff list to the Computer Laboratory.'),
    (34, 'HR',        'COMLAB',    'user_accounts',              'HR sends user account data to the Computer Laboratory.')
) as v(flow_order, sender_code, receiver_code, record_type_code, notes)
join public.departments s on s.department_code = v.sender_code
join public.departments r on r.department_code = v.receiver_code
join public.integration_record_types t on t.record_type_code = v.record_type_code
on conflict (sender_department_id, receiver_department_id, record_type_id) do nothing;

create or replace view public.integration_route_summary as
select
  s.department_name as sender_department,
  r.department_name as receiver_department,
  t.record_type_code,
  t.record_type_name,
  rt.flow_order,
  rt.is_active,
  rt.notes
from public.integration_routes rt
join public.departments s on s.department_id = rt.sender_department_id
join public.departments r on r.department_id = rt.receiver_department_id
join public.integration_record_types t on t.record_type_id = rt.record_type_id
order by rt.flow_order, sender_department, receiver_department;
