-- COMLAB Supabase / PostgreSQL schema
-- Run this file in the Supabase SQL editor.

create extension if not exists pgcrypto;
create schema if not exists comlab;
set search_path to comlab, public;

create or replace function comlab.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Core tables used by the PHP app

create table if not exists comlab.users (
  user_id         bigint generated by default as identity primary key,
  username        text not null unique,
  email           text not null unique,
  password_hash   text not null,
  first_name      text not null,
  last_name       text not null,
  role            text not null check (role in ('Administrator', 'Faculty')),
  hr_employee_id  text unique,
  synced_from_hr  smallint not null default 0 check (synced_from_hr in (0, 1)),
  department      text,
  contact_number  text,
  is_active       smallint not null default 1 check (is_active in (0, 1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  last_login      timestamptz
);

drop trigger if exists trg_users_updated_at on comlab.users;
create trigger trg_users_updated_at
before update on comlab.users
for each row execute function comlab.set_updated_at();

create index if not exists idx_users_role on comlab.users(role);
create index if not exists idx_users_email on comlab.users(email);
create index if not exists idx_users_hr_employee_id on comlab.users(hr_employee_id);
create index if not exists idx_users_active_role on comlab.users(role, is_active);

create table if not exists comlab.user_sessions (
  session_id   bigint generated by default as identity primary key,
  user_id      bigint not null references comlab.users(user_id) on delete cascade,
  auth_token   text not null unique,
  ip_address   text,
  user_agent   text,
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  is_active    smallint not null default 1 check (is_active in (0, 1))
);

create index if not exists idx_user_sessions_token on comlab.user_sessions(auth_token);
create index if not exists idx_user_sessions_user on comlab.user_sessions(user_id);

create table if not exists comlab.locations (
  location_id            bigint generated by default as identity primary key,
  lab_name               text not null,
  lab_code               text not null unique,
  building               text,
  floor                  text,
  room_number            text,
  capacity               integer not null default 0,
  operating_hours_start  time not null default time '08:00',
  operating_hours_end    time not null default time '18:00',
  operating_days         text default 'Monday-Friday',
  description            text,
  is_active              smallint not null default 1 check (is_active in (0, 1)),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_locations_updated_at on comlab.locations;
create trigger trg_locations_updated_at
before update on comlab.locations
for each row execute function comlab.set_updated_at();

create index if not exists idx_locations_lab_code on comlab.locations(lab_code);
create index if not exists idx_locations_active on comlab.locations(is_active);

create table if not exists comlab.devices (
  device_id              bigint generated by default as identity primary key,
  device_code            text not null unique,
  device_type            text not null check (device_type in ('Desktop', 'Laptop', 'Monitor', 'Keyboard', 'Mouse', 'Printer', 'Other')),
  brand                  text,
  model                  text,
  serial_number          text,
  specifications         text,
  purchase_date          date,
  warranty_expiry        date,
  status                 text not null default 'Available' check (status in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  location_id            bigint references comlab.locations(location_id) on delete set null,
  assigned_to            bigint references comlab.users(user_id) on delete set null,
  last_maintenance_date  date,
  next_maintenance_date  date,
  notes                  text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_devices_updated_at on comlab.devices;
create trigger trg_devices_updated_at
before update on comlab.devices
for each row execute function comlab.set_updated_at();

create index if not exists idx_devices_code on comlab.devices(device_code);
create index if not exists idx_devices_status on comlab.devices(status);
create index if not exists idx_devices_location on comlab.devices(location_id);

create table if not exists comlab.device_maintenance_logs (
  maintenance_id     bigint generated by default as identity primary key,
  device_id          bigint not null references comlab.devices(device_id) on delete cascade,
  performed_by       bigint not null references comlab.users(user_id) on delete cascade,
  maintenance_type   text not null check (maintenance_type in ('Repair', 'Preventive Maintenance', 'Inspection', 'Upgrade')),
  issue_description  text,
  action_taken       text,
  parts_replaced     text,
  status_before      text not null check (status_before in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  status_after       text not null check (status_after in ('Available', 'In Use', 'Under Repair', 'Damaged', 'Retired')),
  cost               numeric(10,2) not null default 0.00,
  start_datetime     timestamptz not null default now(),
  end_datetime       timestamptz,
  created_at         timestamptz not null default now()
);

create index if not exists idx_device_maintenance_device on comlab.device_maintenance_logs(device_id);
create index if not exists idx_device_maintenance_performed_by on comlab.device_maintenance_logs(performed_by);

create table if not exists comlab.faculty_schedules (
  schedule_id     bigint generated by default as identity primary key,
  faculty_id      bigint not null references comlab.users(user_id) on delete cascade,
  assigned_by     bigint not null references comlab.users(user_id) on delete cascade,
  location_id     bigint not null references comlab.locations(location_id) on delete cascade,
  class_name      text not null,
  day_of_week     text not null,
  start_time      time not null,
  end_time        time not null,
  duration_hours  numeric(4,2) not null,
  semester_start  date not null,
  semester_end    date not null,
  department      text not null,
  notes           text,
  is_active       smallint not null default 1 check (is_active in (0, 1)),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists trg_faculty_schedules_updated_at on comlab.faculty_schedules;
create trigger trg_faculty_schedules_updated_at
before update on comlab.faculty_schedules
for each row execute function comlab.set_updated_at();

create index if not exists idx_faculty_schedules_faculty on comlab.faculty_schedules(faculty_id);
create index if not exists idx_faculty_schedules_location on comlab.faculty_schedules(location_id);
create index if not exists idx_faculty_schedules_active on comlab.faculty_schedules(is_active);
create index if not exists idx_faculty_schedules_semester on comlab.faculty_schedules(semester_start, semester_end);
create unique index if not exists uq_faculty_schedules_seed_key
  on comlab.faculty_schedules(faculty_id, class_name, semester_start);
alter table comlab.faculty_schedules
  add column if not exists source_system text;
alter table comlab.faculty_schedules
  add column if not exists source_reference text;
alter table comlab.faculty_schedules
  add column if not exists synced_from_hr smallint not null default 0 check (synced_from_hr in (0, 1));
create index if not exists idx_faculty_schedules_source_reference on comlab.faculty_schedules(source_reference);

create table if not exists comlab.schedule_attendance (
  attendance_id    bigint generated by default as identity primary key,
  schedule_id      bigint not null references comlab.faculty_schedules(schedule_id) on delete cascade,
  faculty_id       bigint not null references comlab.users(user_id) on delete cascade,
  attendance_date  date not null,
  status           text not null default 'Absent' check (status in ('Present', 'Absent', 'Excused')),
  checked_in_at    timestamptz,
  marked_by_system smallint not null default 0 check (marked_by_system in (0, 1)),
  notes            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (schedule_id, attendance_date)
);

drop trigger if exists trg_schedule_attendance_updated_at on comlab.schedule_attendance;
create trigger trg_schedule_attendance_updated_at
before update on comlab.schedule_attendance
for each row execute function comlab.set_updated_at();

create index if not exists idx_schedule_attendance_faculty_date on comlab.schedule_attendance(faculty_id, attendance_date);
create index if not exists idx_schedule_attendance_schedule on comlab.schedule_attendance(schedule_id);
create index if not exists idx_schedule_attendance_date on comlab.schedule_attendance(attendance_date);

create table if not exists comlab.lab_usage_logs (
  usage_log_id        bigint generated by default as identity primary key,
  location_id         bigint not null references comlab.locations(location_id) on delete cascade,
  faculty_id          bigint references comlab.users(user_id) on delete set null,
  schedule_id         bigint references comlab.faculty_schedules(schedule_id) on delete set null,
  recorded_by         bigint references comlab.users(user_id) on delete set null,
  usage_date          date not null default current_date,
  session_start       timestamptz not null,
  session_end         timestamptz,
  participant_count   integer not null default 0,
  subject_code        text,
  source_system       text,
  source_reference    text,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (session_end is null or session_end >= session_start)
);

drop trigger if exists trg_lab_usage_logs_updated_at on comlab.lab_usage_logs;
create trigger trg_lab_usage_logs_updated_at
before update on comlab.lab_usage_logs
for each row execute function comlab.set_updated_at();

create index if not exists idx_lab_usage_logs_usage_date on comlab.lab_usage_logs(usage_date);
create index if not exists idx_lab_usage_logs_location on comlab.lab_usage_logs(location_id);
create index if not exists idx_lab_usage_logs_faculty on comlab.lab_usage_logs(faculty_id);
create index if not exists idx_lab_usage_logs_schedule on comlab.lab_usage_logs(schedule_id);
create unique index if not exists uq_lab_usage_logs_source_reference
  on comlab.lab_usage_logs(source_reference)
  where source_reference is not null;

create table if not exists comlab.requests (
  request_id             bigint generated by default as identity primary key,
  request_type           text not null check (request_type in ('Maintenance', 'Unit')),
  submitted_by           bigint not null references comlab.users(user_id) on delete cascade,
  reviewed_by            bigint references comlab.users(user_id) on delete set null,
  department             text not null,
  location_id            bigint references comlab.locations(location_id) on delete set null,
  location_text          text,
  device_id              bigint references comlab.devices(device_id) on delete set null,
  issue_description      text,
  date_needed            date,
  device_type_needed     text,
  specifications_needed  text,
  quantity               integer,
  justification          text,
  status                 text not null default 'Pending' check (status in ('Pending', 'Approved', 'Rejected', 'Completed')),
  rejection_reason       text,
  reviewed_at            timestamptz,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_requests_updated_at on comlab.requests;
create trigger trg_requests_updated_at
before update on comlab.requests
for each row execute function comlab.set_updated_at();

create index if not exists idx_requests_submitted_by on comlab.requests(submitted_by);
create index if not exists idx_requests_status on comlab.requests(status);
create index if not exists idx_requests_created_at on comlab.requests(created_at);

create table if not exists comlab.audit_logs (
  log_id       bigint generated by default as identity primary key,
  user_id      bigint references comlab.users(user_id) on delete set null,
  action_type  text not null,
  target_type  text check (target_type in ('User', 'Device', 'Location', 'Assignment', 'Request', 'Maintenance', 'System')),
  target_id    bigint,
  description  text not null,
  old_value    text,
  new_value    text,
  ip_address   text,
  user_agent   text,
  created_at   timestamptz not null default now()
);

create index if not exists idx_audit_logs_user on comlab.audit_logs(user_id);
create index if not exists idx_audit_logs_action on comlab.audit_logs(action_type);
create index if not exists idx_audit_logs_target on comlab.audit_logs(target_type, target_id);

create table if not exists comlab.login_attempts (
  ip_address     text primary key,
  attempt_count   integer not null default 0,
  last_attempt    timestamptz not null default now(),
  locked_until    timestamptz
);

create index if not exists idx_login_attempts_locked on comlab.login_attempts(locked_until);

-- Department integration tables

create table if not exists comlab.departments (
  department_id    bigint generated by default as identity primary key,
  department_code  text not null unique,
  department_name  text not null unique,
  description      text,
  is_active        smallint not null default 1 check (is_active in (0, 1)),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

drop trigger if exists trg_departments_updated_at on comlab.departments;
create trigger trg_departments_updated_at
before update on comlab.departments
for each row execute function comlab.set_updated_at();

create table if not exists comlab.integration_record_types (
  record_type_id    bigint generated by default as identity primary key,
  record_type_code  text not null unique,
  record_type_name  text not null,
  data_domain       text not null,
  description       text,
  is_active         smallint not null default 1 check (is_active in (0, 1)),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

drop trigger if exists trg_integration_record_types_updated_at on comlab.integration_record_types;
create trigger trg_integration_record_types_updated_at
before update on comlab.integration_record_types
for each row execute function comlab.set_updated_at();

create table if not exists comlab.integration_routes (
  route_id               bigint generated by default as identity primary key,
  flow_order             smallint not null default 1,
  sender_department_id   bigint not null references comlab.departments(department_id) on delete cascade,
  receiver_department_id  bigint not null references comlab.departments(department_id) on delete cascade,
  record_type_id         bigint not null references comlab.integration_record_types(record_type_id) on delete cascade,
  notes                  text,
  is_active              smallint not null default 1 check (is_active in (0, 1)),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (sender_department_id, receiver_department_id, record_type_id)
);

drop trigger if exists trg_integration_routes_updated_at on comlab.integration_routes;
create trigger trg_integration_routes_updated_at
before update on comlab.integration_routes
for each row execute function comlab.set_updated_at();

create index if not exists idx_integration_routes_sender on comlab.integration_routes(sender_department_id);
create index if not exists idx_integration_routes_receiver on comlab.integration_routes(receiver_department_id);
create index if not exists idx_integration_routes_record_type on comlab.integration_routes(record_type_id);

create table if not exists comlab.integration_documents (
  document_id            uuid primary key default gen_random_uuid(),
  route_id               bigint references comlab.integration_routes(route_id) on delete set null,
  record_type_id         bigint not null references comlab.integration_record_types(record_type_id) on delete restrict,
  sender_department_id   bigint not null references comlab.departments(department_id) on delete restrict,
  receiver_department_id bigint not null references comlab.departments(department_id) on delete restrict,
  subject_type           text not null check (subject_type in ('student', 'staff', 'faculty', 'general', 'system')),
  subject_ref            text,
  title                  text not null,
  source_system          text,
  source_reference       text,
  status                 text not null default 'draft' check (status in ('draft', 'sent', 'received', 'acknowledged', 'archived')),
  payload                jsonb not null default '{}'::jsonb,
  sent_at                timestamptz,
  received_at            timestamptz,
  acknowledged_at        timestamptz,
  created_by_user_id     bigint references comlab.users(user_id) on delete set null,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

drop trigger if exists trg_integration_documents_updated_at on comlab.integration_documents;
create trigger trg_integration_documents_updated_at
before update on comlab.integration_documents
for each row execute function comlab.set_updated_at();

create index if not exists idx_integration_documents_status on comlab.integration_documents(status);
create index if not exists idx_integration_documents_sender on comlab.integration_documents(sender_department_id);
create index if not exists idx_integration_documents_receiver on comlab.integration_documents(receiver_department_id);
create index if not exists idx_integration_documents_record_type on comlab.integration_documents(record_type_id);
create index if not exists idx_integration_documents_subject_ref on comlab.integration_documents(subject_ref);
create index if not exists idx_integration_documents_source_reference on comlab.integration_documents(source_reference);

-- Views used by the current COMLAB UI

create or replace view comlab.dashboard_summary as
select
  (select count(*) from comlab.users where is_active = 1) as total_active_users,
  (select count(*) from comlab.users where role = 'Administrator' and is_active = 1) as total_admins,
  (select count(*) from comlab.users where role = 'Faculty' and is_active = 1) as total_faculty,
  (select count(*) from comlab.devices) as total_devices,
  (select count(*) from comlab.devices where status = 'Available') as devices_available,
  (select count(*) from comlab.devices where status = 'Under Repair') as devices_under_repair,
  (select count(*) from comlab.devices where status = 'Damaged') as devices_damaged,
  (select count(*) from comlab.locations where is_active = 1) as total_labs,
  (select count(*) from comlab.faculty_schedules where is_active = 1) as active_schedules,
  (select count(*) from comlab.requests where status = 'Pending') as pending_requests;

create or replace view comlab.faculty_presence_summary as
select
  u.user_id,
  concat(u.first_name, ' ', u.last_name) as faculty_name,
  u.department,
  count(distinct fs.schedule_id) as active_schedules,
  count(sa.attendance_id) as total_sessions,
  sum(case when sa.status = 'Present' then 1 else 0 end) as present_count,
  sum(case when sa.status = 'Absent' then 1 else 0 end) as absent_count,
  sum(case when sa.status = 'Excused' then 1 else 0 end) as excused_count,
  round(100.0 * sum(case when sa.status = 'Present' then 1 else 0 end) / nullif(count(sa.attendance_id), 0), 1) as attendance_rate_pct
from comlab.users u
left join comlab.faculty_schedules fs on fs.faculty_id = u.user_id and fs.is_active = 1
left join comlab.schedule_attendance sa on sa.faculty_id = u.user_id
where u.role = 'Faculty' and u.is_active = 1
group by u.user_id;

create or replace view comlab.integration_message_feed as
select
  d.document_id,
  rt.record_type_code,
  rt.record_type_name,
  sd.department_name as sender_department,
  rd.department_name as receiver_department,
  d.title,
  d.subject_type,
  d.status,
  d.sent_at,
  d.received_at,
  d.created_at
from comlab.integration_documents d
join comlab.integration_record_types rt on rt.record_type_id = d.record_type_id
left join comlab.departments sd on sd.department_id = d.sender_department_id
left join comlab.departments rd on rd.department_id = d.receiver_department_id;


create or replace view comlab.integration_route_summary as
select
  s.department_name as sender_department,
  r.department_name as receiver_department,
  t.record_type_code,
  t.record_type_name,
  rt.flow_order,
  rt.is_active,
  rt.notes
from comlab.integration_routes rt
join comlab.departments s on s.department_id = rt.sender_department_id
join comlab.departments r on r.department_id = rt.receiver_department_id
join comlab.integration_record_types t on t.record_type_id = rt.record_type_id
order by rt.flow_order, sender_department, receiver_department;
